# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gnruxjsM5xyHBR7L2sW6KZkTcuhQRhL1
"""

class triangulo():
  def leerdatos(self):
    self.altura = 10
    self.base = 10
    self.area = 0
  def calculararea(self):
    self.area = (self.base * self.altura)/2
  def imprimir(self):
    print("La Base es: ",self.base)
    print("La Altura es: ",self.altura)
    print("El Área del rectángulo es: ",self.area)

t = triangulo()
t.leerdatos()
t.calculararea()
t.imprimir()